package pixiv

// Generated by https://quicktype.io

// RespOAuthLogin is the response from:
//  POST https://oauth.secure.pixiv.net/auth/token
type RespOAuthLogin struct {
	Response OAuthResponse `json:"response"`
}

// ProfileImageUrls is embedded in RespOAuthLogin
type ProfileImageUrls struct {
	PX16X16   string `json:"px_16x16"`
	PX50X50   string `json:"px_50x50"`
	PX170X170 string `json:"px_170x170"`
}

// RespComments is the response from:
//  https://app-api.pixiv.net/v2/illust/comments?illust_id=...
//  https://app-api.pixiv.net/v2/novel/comments?novel_id=...
//  https://app-api.pixiv.net/v1/illust/comment/replies?comment_id=...
type RespComments struct {
	Comments []Comment `json:"comments"`
	NextURL  string    `json:"next_url"`
}

// RespNovels is the response from:
//
//  https://app-api.pixiv.net/v1/user/novels?user_id=...
//  https://app-api.pixiv.net/v1/user/bookmarks/novel?user_id=...&restrict=...
type RespNovels struct {
	Novels        []Novel `json:"novels"`
	RankingNovels []Novel `json:"ranking_novels"`
	// PrivacyPolicy PrivacyPolicy `json:"privacy_policy"`
	NextURL string `json:"next_url"`
}

// RespNovelText is the response from:
//
//  https://app-api.pixiv.net/v1/novel/text?novel_id=...
type RespNovelText struct {
	NovelMarker NovelMarker `json:"novel_marker"`

	NovelText  string `json:"novel_text"`
	SeriesPrev Novel  `json:"series_prev"`
	SeriesNext Novel  `json:"series_next"`
}

// RespIllusts is the response from:
//
//  https://app-api.pixiv.net/v2/illust/mypixiv
//  https://app-api.pixiv.net/v1/illust/new?content_type=...
//  https://app-api.pixiv.net/v1/user/illusts?user_id=...&type=...
type RespIllusts struct {
	Illusts []Illust `json:"illusts"`
	NextURL string   `json:"next_url"`
}

// RespUserDetail is the response from:
//
//  https://app-api.pixiv.net/v1/user/detail?user_id=...
type RespUserDetail struct {
	User             User              `json:"user"`
	Profile          Profile           `json:"profile"`
	ProfilePublicity ProfilePublicity  `json:"profile_publicity"`
	Workspace        map[string]string `json:"workspace"`
}
